spring.application.name=dipArq07m05appWebSB
# CONEXION BD
spring.datasource.negocio.url=jdbc:mysql://localhost:3306/sis_ventas?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.negocio.username=root
spring.datasource.negocio.password=root
spring.datasource.negocio.driver-class-name=com.mysql.cj.jdbc.Driver
# CONEXION BD SEGURIDAD
spring.datasource.security.url=jdbc:mysql://localhost:3306/ejmBDSeguridad?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.security.username=root
spring.datasource.security.password=root
spring.datasource.security.driver-class-name=com.mysql.cj.jdbc.Driver

# logging
logging.level.root=warn
logging.level.org.springframework.boot=warn
logging.level.org.springframework.boot.tomcat=info
logging.level.org.springframework.security=debug
#
logging.level.mx.com.qtx=info
logging.level.mx.com.qtx.dipArq07m05appWebSB.web=off
logging.level.mx.com.qtx.dipArq07m05appWebSB.web.monitoreo=debug
logging.level.org.springframework.security=debug
#
# Configuraciones adicionales para JPA
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
# BANNER SPRING
spring.main.banner-mode=off
# SEGURIDAD
spring.security.user.name=nicolas
spring.security.user.password=toluka
#
#debug=true